-- Migration 007: seed initial data
-- Depends on: 006

INSERT INTO movies (title, description, duration_minutes) VALUES
    ('Movie A', 'Sci-fi', 120),
    ('Movie B', 'Romantic comedy', 95),
    ('Movie C', 'Action blockbuster', 140);

INSERT INTO rooms (name, room_type) VALUES
    ('Hall 1 (Fixed)', 'fixed');

INSERT INTO rooms (name, room_type, max_capacity) VALUES
    ('Hall 2 (Open)', 'open', 80);

-- Seats for Hall 1 (Fixed): 5 rows × 10 seats
INSERT INTO room_seats (room_id, row_num, seat_num)
SELECT (SELECT id FROM rooms WHERE name = 'Hall 1 (Fixed)'), r, s
FROM generate_series(1, 5)  r,
     generate_series(1, 10) s;


-- NOTE: admin password hash must be generated by the app:
--      python -c "from auth.security import hash_password; print(hash_password('Admin1234!'))"
-- Replace the placeholder below before running.
INSERT INTO users (email, password_hash, role) VALUES (
    'admin@example.com',
    '$2b$12$placeholder_replace_with_real_hash',
    'admin'
);

INSERT INTO sessions (movie_id, room_id, starts_at, ends_at) VALUES
    -- Movie A
    ((SELECT id FROM movies WHERE title = 'Movie A'),
     (SELECT id FROM rooms  WHERE name  = 'Hall 1 (Fixed)'),
     '2024-06-01 14:00+00', '2024-06-01 16:00+00'),
    ((SELECT id FROM movies WHERE title = 'Movie A'),
     (SELECT id FROM rooms  WHERE name  = 'Hall 2 (Open)'),
     '2024-06-04 18:00+00', '2024-06-04 20:00+00'),
    -- Movie B
    ((SELECT id FROM movies WHERE title = 'Movie B'),
     (SELECT id FROM rooms  WHERE name  = 'Hall 1 (Fixed)'),
     '2024-06-02 12:00+00', '2024-06-02 13:35+00'),
    ((SELECT id FROM movies WHERE title = 'Movie B'),
     (SELECT id FROM rooms  WHERE name  = 'Hall 2 (Open)'),
     '2024-06-03 16:00+00', '2024-06-03 17:35+00'),
    -- Movie C
    ((SELECT id FROM movies WHERE title = 'Movie C'),
     (SELECT id FROM rooms  WHERE name  = 'Hall 2 (Open)'),
     '2024-06-01 10:00+00', '2024-06-01 12:20+00'),
    ((SELECT id FROM movies WHERE title = 'Movie C'),
     (SELECT id FROM rooms  WHERE name  = 'Hall 1 (Fixed)'),
     '2024-06-02 20:00+00', '2024-06-02 22:20+00'),
    ((SELECT id FROM movies WHERE title = 'Movie C'),
     (SELECT id FROM rooms  WHERE name  = 'Hall 2 (Open)'),
     '2024-06-03 14:00+00', '2024-06-03 16:20+00');
